Repository dormitoryFamilies/BE, pull requests merged in 2024-03, with the labels that each got.

#51 [Feature] 카카오 OAuth2 로그인 기능 구현
  build.gradle
  src/main/java/dormitoryfamily/doomz/TestController.java
  src/main/java/dormitoryfamily/doomz/domain/article/controller/ArticleController.java
  src/main/java/dormitoryfamily/doomz/domain/article/service/ArticleService.java
  src/main/java/dormitoryfamily/doomz/domain/comment/controller/CommentController.java
  src/main/java/dormitoryfamily/doomz/domain/comment/service/CommentService.java
  src/main/java/dormitoryfamily/doomz/domain/member/entity/Member.java
  src/main/java/dormitoryfamily/doomz/domain/member/entity/type/GenderType.java
  src/main/java/dormitoryfamily/doomz/domain/member/repository/MemberRepository.java
  src/main/java/dormitoryfamily/doomz/domain/replyComment/controller/ReplyCommentController.java
  src/main/java/dormitoryfamily/doomz/domain/replyComment/entity/ReplyComment.java
  src/main/java/dormitoryfamily/doomz/domain/replyComment/service/ReplyCommentService.java
  src/main/java/dormitoryfamily/doomz/domain/test/TestHomeController.java
  src/main/java/dormitoryfamily/doomz/domain/wish/controller/WishController.java
  src/main/java/dormitoryfamily/doomz/domain/wish/service/WishService.java
  src/main/java/dormitoryfamily/doomz/global/jwt/JWTAuthorizationFilter.java
  src/main/java/dormitoryfamily/doomz/global/jwt/JWTKey.java
  src/main/java/dormitoryfamily/doomz/global/jwt/JWTProperties.java
  src/main/java/dormitoryfamily/doomz/global/jwt/JWTUtil.java
  src/main/java/dormitoryfamily/doomz/global/jwt/SigningKeyResolver.java
  src/main/java/dormitoryfamily/doomz/global/oauth2/OAuth2LoginSuccessHandler.java
  src/main/java/dormitoryfamily/doomz/global/oauth2/OAuth2UserService.java
  src/main/java/dormitoryfamily/doomz/global/security/config/SecurityConfig.java
  src/main/java/dormitoryfamily/doomz/global/security/dto/KakaoMemberResponse.java
  src/main/java/dormitoryfamily/doomz/global/security/dto/PrincipalDetails.java
  src/main/resources/application-dev.yml
Labels: enhancement, feature

#53 [Fix] application-prod 파일에 카카오 OAuth 정보 추가
  src/main/resources/application-prod.yml
Labels: bug

#54 [Fix] 카카오 리다이렉트 주소 수정
  src/main/resources/application-prod.yml
Labels: bug

#56 [Setting] 모든 경로에 대한 시큐리티 설정 허용
  src/main/java/dormitoryfamily/doomz/global/security/config/SecurityConfig.java
Labels: setting

#62 [Feature] 멤버 팔로우 및 프로필 조회 기능 구현
  src/main/java/dormitoryfamily/doomz/domain/follow/controller/FollowController.java
  src/main/java/dormitoryfamily/doomz/domain/follow/controller/FollowControllerAdvice.java
  src/main/java/dormitoryfamily/doomz/domain/follow/entity/Follow.java
  src/main/java/dormitoryfamily/doomz/domain/follow/exception/AlreadyFollowingException.java
  src/main/java/dormitoryfamily/doomz/domain/follow/exception/CannotFollowYourselfException.java
  src/main/java/dormitoryfamily/doomz/domain/follow/exception/NotFollowingMemberException.java
  src/main/java/dormitoryfamily/doomz/domain/follow/repository/FollowRepository.java
  src/main/java/dormitoryfamily/doomz/domain/follow/service/FollowService.java
  src/main/java/dormitoryfamily/doomz/domain/member/controller/MemberController.java
  src/main/java/dormitoryfamily/doomz/domain/member/controller/MemberControllerAdvice.java
  src/main/java/dormitoryfamily/doomz/domain/member/dto/response/MemberProfileListResponseDto.java
  src/main/java/dormitoryfamily/doomz/domain/member/dto/response/MemberProfileResponseDto.java
  src/main/java/dormitoryfamily/doomz/domain/member/entity/Member.java
  src/main/java/dormitoryfamily/doomz/domain/member/exception/MemberNotExistsException.java
  src/main/java/dormitoryfamily/doomz/domain/member/service/MemberService.java
  src/main/java/dormitoryfamily/doomz/global/exception/ErrorCode.java
Labels: enhancement, feature
